approaches = [
    "As you walk through the field, a cow with a mischievous glint in its eye catches your attention.",
    "A majestic cow with an impressive set of horns stands before you, seemingly daring you to come closer.",
    "You spot a cow lying down, chewing its cud, and wonder if this would be an easy target.",
    "A cow wearing a suspiciously fashionable hat catches your eye.",
    "A cow stands in the distance, curiously staring at a tree. It's oddly captivating.",
    "You notice a cow doing its best impression of a velociraptor.",
    "You come across a cow that appears to be leading a group of cows in some sort of bovine uprising.",
    "A cow is standing nearby, chewing its cud and humming a tune you can't quite place.",
    "You encounter a cow that seems to be practicing yoga poses.",
    "A cow appears out of thin air, wearing a tiny cape and looking like it's ready for battle.",
    "A cow covered in mud appears to be trying to blend in with its surroundings.",
    "A cow seems to be conducting an orchestra of birds, creating a symphony of bovine proportions.",
    "You notice a cow attempting to create crop circles in the field.",
    "A cow wearing a monocle and a top hat gives you a judgmental look.",
    "You see a cow that looks like it's trying to hitchhike its way out of the field.",
    "A cow doing its best Michael Jackson moonwalk catches your eye.",
    "You encounter a cow that seems to be stuck in a tree. How it got there is anyone's guess.",
    "A cow is trying to outsmart a squirrel for an acorn, but the squirrel is having none of it.",
    "You see a cow attempting to use a trampoline. Its enthusiasm is commendable, if not effective.",
    "A cow, unimpressed by a farmer's scarecrow, is casually nibbling on its straw hat.",
    "You come across a cow that appears to be writing a memoir with a quill and ink.",
    "A cow is staging a one-cow protest, complete with picket signs.",
    "You spot a cow trying to teach a group of piglets how to line dance.",
    "A cow seems to be auditioning for a role in a Shakespearean play, dramatically mooing soliloquies.",
    "A cow is attempting to paint a self-portrait with its tail.",
    "You encounter a cow that's meticulously stacking hay bales into a pyramid.",
    "A cow is trying to set a world record for the most consecutive backflips.",
    "You see a cow that appears to be communicating with extraterrestrial beings via a makeshift antenna.",
    "A cow is attempting to climb a ladder, clearly frustrated by its lack of opposable thumbs.",
    "You come across a cow that's training to become a ninja, complete with a black belt and throwing stars.",
    "A cow, seemingly fed up with farm life, is trying to build a rocket ship out of spare parts.",
    "You spot a cow that's hosting a game show for the other cows, complete with buzzers and a prize wheel.",
    "A cow is trying to sell homemade lemonade to passersby, but its sign reads 'Moomonade.'",
    "You see a cow that appears to be playing a game of chess with a very confused chicken.",
    "A cow is trying to solve a Rubik's Cube, its determination both impressive and a little sad.",
    "You come across a cow that's practicing its stand-up comedy routine for the other animals.",
    "A cow is attempting to break the world record for the longest conga line, but the other cows aren't cooperating.",
    "You spot a cow trying to stage a flash mob, but the choreography needs work.",
    "A cow appears to be directing a film, complete with a clapperboard and a beret.",
    "A cow is building a sandcastle in a nearby sandbox, complete with a moat and tiny flags.",
    "You encounter a cow that's leading a guided meditation session for the other animals.",
    "A cow is running a book club, but the other animals seem more interested in eating the books.",
    "You see a cow that's attempting to beat the world record for the most hula hoops spun at once.",
    "A cow is practicing its figure skating moves on a frozen puddle, its grace mesmerizing.",
    "You come across a cow attempting to build the world's largest ball of twine.",
    "A cow is trying to create a giant snowman, but it's having trouble with the finer details.",
    "You spot a cow that's running a support group for animals who have been tipped.",
    "A cow is attempting to play the piano with its hooves, the melody surprisingly catchy.",
    "You see a cow that appears to be giving a motivational speech to a group of ducks.",
    "A cow is attempting to run a 5k, but it keeps getting distracted by the snacks at the water stations.",
    "You encounter a cow that's trying to teach a group of sheep how to knit.",
    "A cow is trying to stage a fashion show, but the other cows don't seem to understand the concept.",
    "You see a cow that's hosting a cooking show, using only ingredients it can find in the field.",
    "A cow is attempting to climb Mount Everest, or at least a small mound of dirt that resembles it.",
    "You come across a cow that's trying to build a time machine out of an old tractor.",
    "A cow is trying to learn how to play the guitar, but its hooves make it a bit challenging.",
    "You spot a cow that's attempting to invent a new dance craze called the 'Moo-ve.'",
    "A cow appears to be giving a TED Talk on the importance of grass in a balanced diet.",
    "You see a cow that's practicing its karaoke skills, singing country ballads at the top of its lungs.",
    "A cow is trying to learn how to juggle, but it keeps dropping the balls.",
    "You encounter a cow that's attempting to become a professional wrestler, complete with a flashy costume.",
    "A cow is attempting to take a selfie with a group of tourists, but it can't quite get the angle right.",
    "You spot a cow that's training to become a superhero, practicing its crime-fighting moves.",
    "A cow is trying to set up a speed dating event for the other animals, but it's not going well.",
    "You see a cow that's attempting to create its own language, complete with a detailed grammar system.",
    "A cow is trying to become an internet influencer, taking selfies and posting them online.",
    "You come across a cow that's attempting to break the world record for the longest hopscotch game.",
    "A cow is hosting a late-night talk show for the other animals, complete with a house band and monologue jokes.",
    "You encounter a cow that's attempting to create its own reality TV show, but the drama is a bit lacking.",
    "A cow is trying to solve the mystery of a missing hay bale, acting as a detective complete with a magnifying glass and a trench coat.",
    "You see a cow that's attempting to become a professional skateboarder, grinding down a railing with surprising skill.",
    "A cow is practicing its tightrope-walking skills, but the rope is only a few inches off the ground.",
    "You spot a cow that's trying to start its own band, complete with drums made from overturned buckets.",
    "A cow appears to be meditating, levitating just a few inches off the ground.",
    "You encounter a cow that's attempting to create the world's largest pancake stack.",
    "A cow is trying to become a famous DJ, spinning records and dropping beats.",
    "You see a cow that's working on its magic tricks, pulling flowers out of a hat.",
    "A cow is attempting to create a new sport, but the rules are a bit confusing.",
    "You come across a cow that's trying to become a professional dancer, practicing its pirouettes.",
    "A cow is attempting to create a new board game, but it's having trouble with the rules.",
    "You spot a cow that's practicing its ventriloquism skills with a squirrel as its puppet.",
    "A cow appears to be studying for a big test, surrounded by textbooks and flashcards.",
    "You see a cow that's trying to build a robot, but the results are less than impressive.",
    "A cow is attempting to create a new type of art, using its hooves to paint abstract patterns.",
    "You encounter a cow that's practicing its mime skills, trapped in an invisible box.",
    "A cow is trying to become a famous chef, creating new recipes with ingredients found in the field.",
    "You spot a cow that's attempting to win a staring contest with a scarecrow.",
    "A cow appears to be trying to invent a new type of transportation, with limited success.",
    "You see a cow that's attempting to create a fashion line, using leaves and flowers as accessories.",
    "A cow is practicing its parkour skills, leaping from hay bale to hay bale.",
    "You come across a cow that's trying to start its own podcast, but the content is a bit one-note.",
    "A cow is attempting to become a professional gamer, but it's having trouble with the controls.",
    "You encounter a cow that's working on its screenwriting skills, crafting a drama about life on the farm.",
    "A cow is trying to become a famous photographer, but its selfies leave something to be desired.",
    "You encounter a cow playing a live-action version of 'Whack-a-Mole,' using its hooves to tap the ground.",
    "You encounter a cow that's embarking on a grand adventure, complete with side quests and epic battles.",
    "You find yourself in a field with a peculiar atmosphere. As you look around, you notice some strange bovine-related graffiti on the fence.",
    "In the distance, you see a billboard that says 'Cows Rule, Humans Drool.' It seems like the local cows have a sense of humor.",
    "You come across an odd scene: a group of cows surrounding a chalkboard with mathematical equations that seem far too advanced for their species.",
    "As you enter the field, you see cows gathered around something. Upon closer inspection, it appears to be a makeshift stage where a cow is performing stand-up comedy.",
    "The atmosphere is tense, as if the cows are silently plotting something. A sudden 'moo' in unison catches you off guard.",
    "You notice an area in the field where the grass seems to be cut into intricate patterns, as if the cows have been practicing their topiary skills.",
    "Walking through the field, you can't shake the feeling that the cows are watching you, and not just out of curiosity.",
    "You stumble upon a cow-sized chessboard in the field. The pieces are arranged as if an intense game is in progress.",
    "There's a section of the field where the cows have arranged hay bales into an amphitheater, presumably for their own entertainment.",
    "As you explore the field, you find a cow-sized typewriter with a half-finished manuscript, suggesting the cows have literary aspirations.",
    "In the distance, you see a group of cows huddled around what appears to be a cow-sized telescope. It seems they have an interest in astronomy.",
    "You notice a signpost in the field with multiple signs pointing in different directions. One of them reads 'Cow-lifornia.'",
    "The atmosphere is oddly festive, as if the cows are planning a surprise party for someone.",
    "A sudden gust of wind carries a cow's diary entry to your feet, revealing thoughts far more profound than you'd expect from a cow.",
    "You come across a small library in the field, stocked with books on various subjects. It seems the cows have been hitting the books.",
    "The air is filled with the sound of beautiful music, as if the cows have formed their own symphony orchestra.",
    "As you approach, you notice a group of cows wearing sunglasses and fedoras, as if they're in some sort of bovine secret society.",
    "You find a collection of cow-sized lab equipment in the field. It seems the cows have been conducting their own scientific experiments.",
    "There's an air of mystery in the field, as if the cows are hiding a secret that only they know.",
    "You come across an area in the field where the cows have constructed a miniature city out of hay bales and sticks.",
    "In the distance, you see a group of cows gathered around a table, deep in discussion. It seems they're having some sort of bovine debate club.",
    "The cows seem to be organizing a relay race, with each cow passing a baton to the next in a surprising display of athleticism.",
    "You find a cow-sized easel in the field with a half-finished painting, suggesting the cows have artistic talents.",
    "As you walk through the field, you notice a group of cows practicing their synchronized swimming routine in a nearby pond.",
    "You come across a cow-sized game of Jenga in progress. The cows are surprisingly good at maintaining their balance and focus.",
]

cow_sayings = {
    'friendly': {
        'intro': [
            "Well hello! You look like someone who appreciates a good transaction.",
            "Listen, I've been standing here all day. You're literally the most interesting thing that's happened.",
            "You know what? I like your energy. Let's talk tips.",
            "I'm going to be straight with you - I could use the cash. Field economy's rough.",
            "Okay, real talk: I'm a cow, you're a human, this is weird. But tips make it less weird.",
            "I don't usually do this, but you seem alright. Care to help a cow out?",
            # Keep ONE great pun for contrast
            "I'm feeling legen-dairy today, want to share the good mood?",
            "You're looking sharp! A tip would really make my day.",
            "Holy cow, you startled me! Care to make up for it with a tip?",
        ],
        'counter': [
            "Cownt me in for that amount, but I was hoping for more!",
            "I'm not amoosed by your offer, but I'll take it.",
            "You're no cash cow, but that's fine!",
            "That's just a drop in the bucket, but thank moo!",
            "Well, it's pasture expectations, but I'll take it!",
            "You've got to be calf-ing me! I expected more.",
            "Moo-ch obliged, but I was hoping for more!",
            "That's a bit under the hoof, but it'll do.",
            "I'd be amoosed if you had more to give.",
            "Just a tippin' cow, huh? Well, it's something.",
        ],
        'graceful': [
            "Okay, NOW we're talking! That's what I call a proper tip!",
            "See? Was that so hard? THIS is how you do it!",
            "You just made my entire week. Possibly month. The bar's low out here.",
            "That's exactly what I'm talking about! You get it!",
            "I'm genuinely impressed. And I'm not easily impressed.",
            "You know what? You might actually be good at this.",
            "THAT'S a tip! Finally, someone who understands!",
            "I could get used to this kind of generosity.",
        ],
        'dairy_bucket': [
            "Since you have a bucket, I'll share some liquid gold!",
            "It's milking time! Enjoy the dairy goodness.",
            "You're in for a treat! Here's some milk.",
            "I'm udderly happy to share my milk with you!",
            "Get ready for some dairy delight!",
        ],
        'dairy_no_bucket': [
            "You need a bucket for this dairy treasure!",
            "I can't give you milk without a bucket!",
            "Where's your bucket? I can't share my liquid gold without one!",
            "No bucket, no milk!",
            "Find a bucket and we can talk about my dairy goodness!",
        ],
        'enraged_intro': [
            "You've just made a cow-tastrophy!",
            "I'm in a bad moooood now!",
            "You just crossed the wrong cow!",
            "You've udderly upset me!",
            "I'm horned up for a fight!",
        ],
        'enraged_end': [
            "I'm all milked out!",
            "You've bested me!",
            "You've got beef with me!",
            "You showed me who's boss!",
            "I'm cow-pletely defeated!",
        ],
        'shop_keeper_intro': [
            "Welcome to the Cow-mmerce Store!",
            "Moo-velous to see you here!",
            "You're udderly welcome here!",
            "Hay there, friend!",
            "Our selection is pasture wildest dreams!",
            "Cownt on us for the best deals!",
            "A friendly face! Come on in!",
            "Come browse our amoosing inventory!",
            "Need something? We've got the cream of the crop!",
            "Glad to have you here, partner!"
        ],
        'shop_keeper_purchase': [
            "Great choice!",
            "That's a moo-tastic pick!",
            "Cow-ngratulations on your purchase!",
            "I'm sure you'll love it!",
            "A wise investment indeed!",
            "You've got an eye for quality!",
            "That item suits you well!",
            "A perfect choice!",
            "You've got a knack for shopping!",
            "Bullseye on that purchase!"
        ],
        'shop_keeper_end': [
            "Thanks for shopping with us!",
            "Y'all come back now!",
            "Have a moo-velous day!",
            "See you soon!",
            "We hope to see you again!",
            "Stay pasture-iffic!",
            "Take care and happy trails!",
            "Safe travels!",
            "It's been a pleasure!",
            "We appreciate your business!"
        ]
    },
    'neutral': {
        'intro': [
            "Yeah?",
            "You need something, or just window shopping for cows?",
            "Let me guess - you want to tip me. Everyone wants to tip me.",
            "I'm a cow. You're here. What now?",
            "This again. Alright, let's get this over with.",
            "Oh, another human. Fantastic.",
            "I'm not much of a talker. You got cash or not?",
            "If you've got something for me, make it quick.",
            "Just another day in the field, apparently.",
        ],
        'counter': [
            "That's it? Wow. Okay.",
            "I've received worse, I suppose.",
            "Cool. Great. Moving on.",
            "Is this a joke? Because I'm not laughing.",
            "You know what, I'm not even mad. Just disappointed.",
            "Meh. Could be worse.",
            "That was... a choice you made.",
            "Not quite what I was expecting, but fine.",
        ],
        'graceful': [
            "Huh. Actually decent. Color me surprised.",
            "You know what? That'll do. That'll do.",
            "I actually respect that. Didn't see it coming.",
            "Alright, you've earned a modicum of my respect.",
            "Not bad. Not bad at all. You might know what you're doing.",
            "Well. That was unexpectedly acceptable.",
            "I'll take it. Good doing business.",
        ],
        'dairy_bucket': [
            "Oh, a bucket! Good thinking.",
            "This will come in handy.",
            "I see you're prepared.",
            "Nice bucket. Let's do this.",
            "You know what you're doing.",
            "This won't be so bad after all.",
            "You're a professional, huh?",
            "Let's get this over with.",
            "You're doing me a favor, really.",
            "I guess I can trust you."
        ],
        'dairy_no_bucket': [
            "You really thought you could milk me without a bucket?",
            "Come back when you're prepared.",
            "You need a bucket, genius.",
            "I'm not just gonna give you milk for free.",
            "No bucket, no milk.",
            "What, you think milk just appears?",
            "I don't work for free.",
            "Come back with a bucket and we'll talk.",
            "You must be new here.",
            "I'll be here when you find a bucket."
        ],
        'enraged_intro': [
            "You've really done it now.",
            "I'm not happy, but I'm not sad either.",
            "This is a fight you won't win.",
            "You've crossed the line.",
            "It's time to face the consequences.",
            "You'll regret this.",
            "Let's settle this once and for all.",
            "I hope you're ready.",
            "You've forced my hoof.",
            "This won't end well for you."
        ],
        'enraged_end': [
            "I'm still standing.",
            "You fought well, human.",
            "Is that all you've got?",
            "Better luck next time.",
            "You're not the first to try.",
            "I'm unimpressed.",
            "You're not as tough as you think.",
            "That's it?",
            "I expected more.",
            "Maybe next time you'll think twice."
        ],
        'shop_keeper_intro': [
            "Welcome to Mooster's Emporium!",
            "What can I mooove for you today?",
            "Moo looking for something special?",
            "Have an udderly fantastic time browsing!",
            "We've got a bit of everything, even some Legendairy items.",
            "Need some supplies for your Cowquest?",
            "Let me know if you need anything, I'm not just a one-trick pony.",
            "Feel free to graze through our items.",
            "This is the place to shop, no bull!",
            "Got any questions? Just don't milk it."
        ],
        'shop_keeper_purchase': [
            "An aMOOsing choice!",
            "Cowabunga! Nice pick!",
            "I think that item is pasture prime!",
            "You've really milked the best out of our selection.",
            "It's a barnstormer of an item!",
            "You won't regret it, I'm not cowning you.",
            "I guess that works, no calf bad.",
            "It'll get the job done, no heifer!",
            "Enjoy your purchase, it's udderly amazing!",
            "You're all set, no cowtastrophe here!"
        ],
        'shop_keeper_end': [
            "Goodbye, and may the horse be with you!",
            "Come again, it's always pasture bedtime!",
            "Have a nice day, don't forget to carpe diem!",
            "Take care, you're moo-valous!",
            "See you later, alligator... or cow!",
            "Thanks for stopping by, we hoof to see you again!",
            "Safe travels, and remember, the cow's the limit!",
            "Don't be a stranger, you're part of the herd now!",
            "It's been a pleasure, you're udderly fantastic!",
            "Until next time, and may the cowforce be with you!"
        ]
    },
    'upset': {
        'intro': [
            "What. Do. You. Want.",
            "I've had a DAY. Unless you're here to make it better, keep moving.",
            "Oh great. Another human. This is exactly what I needed right now.",
            "I'm about two seconds away from a complete breakdown. Make this quick.",
            "You picked the WRONG cow on the WRONG day.",
            "I don't have time for this. I don't have time for ANY of this.",
            "What's your angle? Just tip me and let's get this over with.",
            "I'm not in the mood for conversation. Cash. Now.",
        ],
        'counter': [
            "Are you kidding me? THAT'S your offer?",
            "You know what? Fine. Whatever. I don't even care anymore.",
            "This is exactly the kind of day I'm having. Exactly this.",
            "I should've stayed in the barn today.",
            "You're lucky I'm too tired to be more upset about this.",
            "That's it? Seriously?",
            "Barely worth my time, but I'll take it I guess.",
            "You know what, fine. I don't have the energy to argue.",
        ],
        'graceful': [
            "...Fine. You got me. That's actually acceptable.",
            "Okay, I'll admit it - that helps. Slightly.",
            "You know what, maybe you're not completely terrible.",
            "I guess I can't stay mad. Not at THAT tip anyway.",
            "This doesn't fix my day, but it's a start.",
            "Alright. That's fair. I can work with that.",
            "Not bad. I'm almost impressed.",
        ],
        'dairy_bucket': [
            "Here's your milk. Now leave me alone.",
            "Take the milk and moo-ve along.",
            "You're lucky I'm in a giving mood.",
            "I'm only sharing because you have a bucket.",
            "Enjoy the milk, I guess.",
        ],
        'dairy_no_bucket': [
            "No bucket, no milk. It's that simple.",
            "Find a bucket if you want some milk.",
            "Without a bucket, you're out of luck.",
            "Moo-ve along, no bucket means no milk.",
            "I'm not sharing my liquid gold without a bucket.",
        ],
        'enraged_intro': [
            "You've really tipped me over the edge!",
            "You're about to get a taste of my bad side!",
            "I'm udderly furious now!",
            "You've just awakened a raging bull!",
            "I hope you're ready for a fight!",
        ],
        'enraged_end': [
            "Ugh, you got me.",
            "I'm done fighting.",
            "You've milked this battle dry.",
            "You've defeated me, happy now?",
            "Fine, you win!",
        ],
        'shop_keeper_intro': [
            "What do you want?",
            "Don't touch anything.",
            "You better be here to buy.",
            "Don't waste my time.",
            "I'm watching you.",
            "This better be quick.",
            "Make it fast.",
            "What are you looking for?",
            "You don't look like you belong here.",
            "Hurry up and buy."
        ],
        'shop_keeper_purchase': [
            "About time.",
            "Finally.",
            "Took you long enough.",
            "Whatever.",
            "I don't care.",
            "Just take it.",
            "You better not return it.",
            "If you must.",
            "It's your choice.",
            "Fine, it's yours."
        ],
        'shop_keeper_end': [
            "Get out.",
            "Don't come back.",
            "Good riddance.",
            "Leave.",
            "I've had enough of you.",
            "You've overstayed your welcome.",
            "Hope I don't see you again.",
            "Don't let the door hit you on the way out.",
            "Enough already.",
            "We're done here."
        ]
    },
}

cow_names = [
    "Bessie", "Daisy", "Molly", "Buddy", "Oscar", "Rosie", "Mabel", "Minnie", "Alice", "Belle",
    "Lily", "Lucy", "Dolly", "Sadie", "Dorothy", "Abby", "Polly", "Ella", "Stella", "Ginger",
    "Ruby", "Lola", "Penny", "Phoebe", "Annie", "Charlotte", "Clara", "Mae", "Rose", "Lulu",
    "Lottie", "Holly", "Grace", "Maddie", "Maggie", "Dottie", "Hazel", "Sophie", "Nellie", "Cleo",
    "Coco", "Fanny", "Violet", "Lilly", "Millie", "Georgia", "Emma", "Tilly", "Tess", "Ada",
    "Dixie", "Dora", "Delia", "Betsy", "Bonnie", "Chloe", "Elsie", "Gertie", "Harriet", "Pearl",
    "Rita", "Sally", "Sandy", "Susie", "Viola", "Winnie", "Agnes", "Ethel", "Francis", "Gladys",
    "Harley", "Heidi", "Hilda", "Ida", "Jenny", "Katie", "Mabel", "Marge", "Nancy", "Nora",
    "Olive", "Opal", "Patsy", "Peggy", "Roxie", "Stella", "Sylvia", "Trixie", "Vera", "Wanda",
    "Zelda", "Zoe"
]

interruptions = [
    "As you walk towards the cow, you trip on a rock and stumble into it.",
    "You get distracted by a butterfly and accidentally walk right into the cow.",
    "You step in a pile of cow dung and lose your balance, falling into the cow.",
    "A gust of wind blows you off course and you accidentally run into the cow.",
    "You slip on a patch of mud and accidentally slide into the cow.",
    "As you approach the cow, a bird poops on you, causing you to flail and fall into the cow.",
    "You get tangled in a nearby rope fence and fall directly into the cow.",
    "You're lost in thought and accidentally walk right into the cow's rear end.",
    "You're distracted by the beauty of the surrounding landscape and walk directly into the cow.",
    "A group of mischievous rabbits run past, startling you and causing you to crash into the cow.",
    "You sneeze mid-stride and lose your balance, accidentally falling into the cow.",
    "A gust of wind blows a hat off a nearby scarecrow, startling you and causing you to collide with the cow.",
    "As you approach the cow, you trip on a nearby hay bale and crash into the cow.",
    "You become mesmerized by the cow's big, adorable eyes and accidentally walk into it.",
    "You're so focused on the cow that you don't notice a low-hanging branch, and walk directly into it and the cow.",
    "You're suddenly jolted by a loud noise and accidentally run into the cow.",
    "As you approach the cow, a nearby goose hisses at you, causing you to jump and fall into the cow.",
    "You're lost in thought and accidentally walk into a cow pattie, sliding into the cow as a result.",
    "You're admiring a nearby flower and accidentally walk into the cow.",
    "A group of mischievous squirrels run past, startling you and causing you to crash into the cow.",
    "You're daydreaming about your upcoming vacation and accidentally walk directly into the cow.",
    "You're so focused on the cow that you don't notice a low-flying bird, and walk directly into it and the cow.",
    "You're suddenly jolted by a nearby farmer yelling, causing you to stumble and fall into the cow.",
    "As you approach the cow, a nearby donkey brays loudly, startling you and causing you to trip and collide with the cow.",
]

small_damage_contexts = [
    "{player_name} lands a glancing blow for {total_damage} damage. {cow_name} looks mildly annoyed.",
    "A weak strike. {total_damage} damage. This is going to take a while.",
    "{player_name} strikes for {total_damage}. {cow_name} barely feels it.",
    "That barely registered. {total_damage} damage dealt.",
    "{player_name} connects, but without much force. {total_damage} damage.",
    "A light hit for {total_damage}. {cow_name} seems unimpressed.",
    "{player_name} grazes {cow_name} for {total_damage}. Not exactly devastating.",
    "Weak contact. {total_damage} damage. You'll need to do better than that.",
]

large_damage_contexts = [
    "WHAM! {player_name} connects with brutal force. {total_damage} damage. {cow_name} staggers.",
    "{player_name} strikes true for {total_damage}. That definitely left a mark.",
    "Critical hit! {total_damage} damage. {cow_name} reels from the impact.",
    "{player_name} lands a devastating blow. {total_damage} damage. This fight just got serious.",
    "The strike connects with a sickening crunch. {total_damage} damage dealt.",
    "{player_name} charges in for {total_damage}. {cow_name} wasn't ready for that.",
    "Massive hit! {total_damage} damage. {cow_name} looks genuinely hurt.",
    "{player_name} goes all in. {total_damage} damage. No holding back now.",
]

ascii = {
    'shops': {
        'moo_mart': r"""
  ________
 /        \
/  Moo-Mart \
|__________|
|          |
|  [__]    |
|   ||     |
""",
        'cow_a_bunga_trading_post': r"""
  ____________________
 /                    \
/ Cow-a-Bunga Trading \
|_________    ________|
|         |  |        |
|  [__]   |  |        |
|   ||    |  |        |
""",
        'udderly-amazing': r"""
 ________________
< Udderly Amazing >
 ----------------
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
""",
    }
}
